# Generated by Django 5.0.6 on 2024-07-10 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock_status',
        ),
    ]
