# Generated by Django 5.0.6 on 2024-07-10 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_remove_productcategory_slug'),
        ('product', '0006_remove_product_stock_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockStatus',
        ),
    ]
