# Generated by Django 5.0.6 on 2024-07-16 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_delete_stockstatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogCategory',
        ),
    ]
